FROM python:3.12-alpine
LABEL organization=AI2C
LABEL version=1.0

# install django
RUN apk update
RUN pip install django

# setup user
RUN addgroup -g 1001 django && \
    adduser -u 1001 -G django -s /bin/sh -D django

# setup folder
RUN mkdir /todo_django
RUN chown django:django /todo_django
RUN chmod -R +rwx /todo_django
ADD todo_django /todo_django

VOLUME ["/data"]

# runtime settings
USER django
WORKDIR /todo_django
EXPOSE 8000
ENV DJANGO_DEBUG=True
ENTRYPOINT ["/bin/sh", "startup.sh"]

HEALTHCHECK --interval=15s --timeout=10s --start-period=60s \
    CMD curl -f http://localhost/ || exit 1